twig:
    default_path: '%kernel.project_dir%/templates'
    # Th√®me Boostrap pour les forms
    form_themes:
        - 'boostrap_5_layout.html.twig'

when@test:
    twig:
        strict_variables: true
